### ISSUE TITLE
[Feature]: Documentation on extending Rivet Functionality

### ISSUE THREAD

**Issue by aaronsantiago** [Ironclad/rivet#105]
### Feature Request

Right now the only reference we have for adding custom nodes is the [calculate external function hidden in the rivet example](https://github.com/Ironclad/rivet-example/blob/main/server/src/services/RivetRunner.ts), briefly referenced in the video on the website.

I'm sure many use cases will rely on using special nodes so it would be nice if we had clearer documentation on external calls: https://rivet.ironcladapp.com/docs/node-reference/external-call

and plugins: https://rivet.ironcladapp.com/docs/user-guide/plugins/creating-plugins

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Yes thanks for calling this out! I didn't have time to finish these parts of the documentation. 

Custom nodes are really for the realm of plugins - many custom node functions can be achieved by using a [Subgraph Node](https://rivet.ironcladapp.com/docs/user-guide/subgraphs) so that you can encapsulate one graph in another. Combined with a Code Node, there's a lot you can achieve this way. Plugins are more necessary for actions that "break out" of Rivet and do things like HTTP calls.

**Comment by aaronsantiago** [comment]
Good to know--things like making calls to Play.ht or using local LLM endpoints are what I'm really looking to do to get the most from Rivet right now.

From what I can tell, the best way to make a plugin is to build Rivet from source and add the plugin into the built-in list. I see that there is a system for remote plugins, but I haven't been able to find any examples of how to build/host one. Are there any lying around?

**Comment by abrenneke** [comment]
I haven't actually tested the remote plugin stuff at all yet @aaronsantiago 😅 it relied on Rivet being open-sourced, so I couldn't test it before then. It's probably bugged in some way.

> From what I can tell, the best way to make a plugin is to build Rivet from source and add the plugin into the built-in list. 

That's the most sure-fire way right now, yeah.

**Comment by abrenneke** [comment]
You can also check out the new `HTTP Call` node I just added to `main`, should make certain integrations easier and not require plugins.

**Comment by aaronsantiago** [comment]
For posterity, both the HTTP Call (https://github.com/Ironclad/rivet/releases/tag/app-v1.3.0-beta1) and plugin system (https://github.com/abrenneke/rivet-plugin-example) are currently available, the latter is documented in that repository.
