### ISSUE TITLE
[Feature]: Support for local models

### ISSUE THREAD

**Issue by andraz** [Ironclad/rivet#106]
### Feature Request

There are many publicly available models that we can run for free on our own hardware.

Example: [TheBloke/Llama-2-13B-chat-GPTQ](https://huggingface.co/TheBloke/Llama-2-13B-chat-GPTQ)

How to execute the Chat in Rivet on these models?

To see implementation refer to this project, where we can use it locally today: https://github.com/oobabooga/text-generation-webui

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
That's something I'd like to support too! I'll check out that project for tips on how to accomplish it.

**Comment by juangea** [comment]
@abrenneke you could simply redirect the request towards an OpenAI compatible API, like the one present in Oobabooga, so you basically maintain everything the same, just allow to redirect the calls for the API to OpenAI Oobabooga API, that's a quick and easy way to support Local models with GPU support :)

**Comment by abrenneke** [comment]
Oh that's a good idea. You'd have to run an instance of whatever API that is but that would be really easy to implement on the Rivet side.

**Comment by abrenneke** [comment]
Something like this? 
![Uploading image.png…]()

**Comment by andraz** [comment]
Looks great, it can be plug and play with this project too: https://github.com/go-skynet/LocalAI

**Comment by abrenneke** [comment]
Yep that's the one I tested with @andraz. This has been pushed to main so I'll close this issue, should be available when 1.2.0 comes out soon.

**Comment by abrenneke** [comment]
Also, we have someone working on a deeper oobabooga integration plugin

**Comment by hushaudio** [comment]
Yep, I have just finished the first version.  It allows for model loading and checking the loaded model.  Any requests welcome, right now it has some chat params, and model loading is done using your saved model loading defaults in oobabooga.

https://github.com/hushaudio/rivet-oobabooga-plugin

Import link
```https://cdn.jsdelivr.net/gh/hushaudio/rivet-oobabooga-plugin@main/dist/oobabooga-rivet.js```
