### ISSUE TITLE
[Feature]: please support Azure OpenAI

### ISSUE THREAD

**Issue by Wannabeasmartguy** [Ironclad/rivet#108]
### Feature Request

Some models can be more easily accessed through Azure. 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Good idea thanks! This is probably good to implement as a plugin.

**Comment by abrenneke** [comment]
Thanks for the tip @mhamadeus it was indeed that easy! Will be in 1.4!

@all-contributors please add @Wannabeasmartguy for idea, and @mhamadeus for idea

**Comment by mhamadeus** [comment]
Thanks @abrenneke! 😊 Confirmed working! As the model is a path param, we use a text input to select the correct model. Works like a charm!

**Comment by abrenneke** [comment]
Great to hear it!
