### ISSUE TITLE
[Feature]: Add the optional Base URL

### ISSUE THREAD

**Issue by CongYun22** [Ironclad/rivet#121]
### Feature Request

Add the optional Base URL feature

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
@CongYun22 where would a base url be helpful? Could you give some more information?

**Comment by CongYun22** [comment]
@abrenneke in that way we can use an unofficial API provider, since using the official one isn't easy in some country like China.

**Comment by abrenneke** [comment]
Will the new HTTP Call node and allowing a custom endpoint in the Chat node help here @CongYun22?

**Comment by CongYun22** [comment]
@abrenneke yes that would be helpful, and adding a custom endpoint in here would be more convenient.
![openai-settings-f64ea80691e78cf6140154b042180207](https://github.com/Ironclad/rivet/assets/115971962/b37e78d8-446f-43bb-8fd8-4d3afe72336e)

**Comment by abrenneke** [comment]
That's a good idea

**Comment by abrenneke** [comment]
Added in cd2a23f4d8cffdc01b1996c6a7face9d28a831d5 thanks @CongYun22! @all-contributors please add @CongYun22 for idea
