### ISSUE TITLE
[Bug]: I have to add plugins every time I open project

### ISSUE THREAD

**Issue by Swimburger** [Ironclad/rivet#129]
### What happened?

Whenever I open my project for the first time, the plugins are not loaded. Can the used plugins be stored inside the project (without sensitive settings), so it will be enabled when we open the project again?

### What was the expected functionality?

The plugins should remain enabled if I enabled them before for a project.

### Describe your environment

MacOS, Node v20.5.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Whoops did I forget to do that?

**Comment by abrenneke** [comment]
Fixed in  37fa543b4d27bfc26a123a88d96fd30b6ddb3ca5
