### ISSUE TITLE
[Feature]: Split/ extract data from JSON formatted outputs

### ISSUE THREAD

**Issue by darthkenobi5319** [Ironclad/rivet#132]
### Feature Request

Currently there are no option to extract several outputs from a JSON-like output (from a chat, for example) and put into multiple entries in another text node by using string interpolation. I think it would be helpful to have this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
@darthkenobi5319 are you wanting something like the `Extract JSON` node, that can extract every json-like object from an input string, instead of just the first one it finds?

**Comment by abrenneke** [comment]
I'll close because I'm not sure what you're looking for but feel free to reopen.
