### ISSUE TITLE
Document how to use node executor when running from source (or how to make builds)

### ISSUE THREAD

**Issue by aaronsantiago** [Ironclad/rivet#133]
### Feature Request

The new HTTP request node is only available on main, however the workflow involves running Rivet through a browser where the browser executor will run into CORS issues very commonly.

The node executor doesn't seem like it's available when running from source, and I couldn't find any information about that or how to make builds.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Oops, there used to be docs about running from source. @aaronsantiago it should be as simple as `yarn dev` in the root of the repo, assuming you have all the prerequisites installed.

**Comment by aaronsantiago** [comment]
Yes, sorry I don't think I was clear.

I cant' access the _node_ executor specifically, when running from source. 

I followed the instructions from the bottom of [this page](https://rivet.ironcladapp.com/docs/getting-started/installation), and ran `yarn dev`. A development server runs and I open the page in my browser.

In the executor dropdown, only the Browser executor is available, which causes CORS errors when making requests to certain endpoints.

**Comment by abrenneke** [comment]
When you run `yarn dev`, it should pop up the full tauri application, you shouldn't have to load Rivet up in your browser. Is it erroring somewhere?

**Comment by aaronsantiago** [comment]
Ah, yes a couple restarts and everything makes sense again. Apologies, seems like something was wrong with my environment!
