### ISSUE TITLE
[Feature]: Flag missing settings that are required to run

### ISSUE THREAD

**Issue by Jkwok0714** [Ironclad/rivet#152]
### Feature Request

When the AI node model is set to take an input but no input is provided, a TypeError throws in the graph node:

![Screenshot 2023-09-14 at 12 46 24 PM](https://github.com/Ironclad/rivet/assets/28716303/94db6a1c-0de7-427c-9300-336fbdbbcc99)

I'm guessing it flagged from one of the variations of this, which is how I eventually found the problem of a missing model:

```ts
const tiktokenModel = openaiModels[model].tiktokenModel;
```

Based on some of the other patterns, such as in text nodes, it seemed like the setting dropdown would specify a default:

<img width="772" alt="Screenshot 2023-09-14 at 2 40 39 PM" src="https://github.com/Ironclad/rivet/assets/28716303/cb08243a-9216-41d2-88d9-09f6ab1ffff3">
<img width="720" alt="Screenshot 2023-09-14 at 2 55 58 PM" src="https://github.com/Ironclad/rivet/assets/28716303/da6bf5af-06bf-40d5-9051-0e160377596e">

I wasn't aware that the input toggle was toggled on so it took a moment to find the issue. Would be awesome if there was some error state, or use the selected one as a default!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Good point thanks!

**Comment by abrenneke** [comment]
Fixed in 828caa6705d324e907a26397dde0e83f56c27d0f

**Comment by abrenneke** [comment]
@all-contributors please add @Jkwok0714 for bug
