### ISSUE TITLE
[Bug]: After adding a faulty plugin in "Add Remote Plugin", no other plugin can be imported

### ISSUE THREAD

**Issue by vibl** [Ironclad/rivet#155]
### What happened?

After adding a faulty plugin in "Add Remote Plugin", no other plugin can be imported: the button on the right is stuck in the "Loading..." state. The project must be reopened before a plugin can be imported again.

### What was the expected functionality?

Pasting a new URL in "Add Remote Plugin" should reset the button.

### Describe your environment

Kubuntu 23.04
rivet_1.2.1_amd64.AppImage

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Fixed in dd488ef5db7b3fd98adc5314dc7fbf4c2c7c50e1, will be in next release, thanks!
