### ISSUE TITLE
[Bug]: the Trim Chat Message Node stops  working when it has to trim

### ISSUE THREAD

**Issue by vibl** [Ironclad/rivet#156]
### What happened?

When Max Token Count is set at above the input size, the Trim Chat Message Node passes on the input to the output intact, as expected.

When it is set below the input size such that the node has to do its trimming job, it stops working (no output).

### What was the expected functionality?

It should trim.

### Describe your environment

Kubuntu 23.04
rivet_1.2.1_amd64.AppImage

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
That's correct @vibl, the trim chat messages node is designed to trim off entire _messages_ to get under a context limit. If you're looking to trim text, you'll want to use the Chunk node.

**Comment by vibl** [comment]
Ok. New users would greatly benefits from in-app contextual documentation. I'm guessing you already have that in your roadmap.
