### ISSUE TITLE
[Feature]: read a textfile and split by line

### ISSUE THREAD

**Issue by temco** [Ironclad/rivet#164]
### Feature Request

how can I split a textfile into lines and store them into a vector-store, like those features in flowise and langflow? thanks!
can node-split cover my request?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Rivet 1.3 will include a Split Text node that will let you split something into an array by new lines! Putting that into a Split Vector Store should get them into the vector store :+1: Just working on publishing now.
