### ISSUE TITLE
[Bug]: tokencounter & cost counter doesn't match node counts by factor of 5+

### ISSUE THREAD

**Issue by wayne-chang** [Ironclad/rivet#171]
### What happened?

When running long graphs with subgraphs, some nodes are showing 5x+ higher counts on the individual nodes while the IDE counter shows a very small number.

### What was the expected functionality?

Token counting and cost counting to be in similar realms between nodes & IDE totals

### Describe your environment

MacOS, Node 20

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gogwilt** [comment]
I think this is largely resolved fy #237.
