### ISSUE TITLE
[Bug]: Remote debugger does not render image data correctly, due to Uint8Array getting messed up by JSON.stringify

### ISSUE THREAD

**Issue by gogwilt** [Ironclad/rivet#179]
### What happened?

I was trying to get GPT-4 to draw using SVGs, and preview the output in Rivet. However, the render was failing. Specifically, I had written an `externalFunction` for converting from SVG text to PNG image. In the Rivet UI, the `value.data` field that should have been a Uint8Array was coming back as an object with numeric keys (eg. `{0: 137, 2: 80, 3: 78, ...}`).

This seems to be a symptom of `JSON.stringify`, when it is used to encode the data object to send over the websocket.

### What was the expected functionality?

I expected the PNG image to render in the node output section.

### Describe your environment

MacOS, Node 20.0.0, etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gogwilt** [comment]
I have a patch for `useCurrentExecution`, `sanitizeDataValueForLength`, which converts from the stringified Uint8Array back into a Uint8Array. I *think* this is the right direction for a fix, because the issue is only in the remote debugger websocket communication AFAIK.

**Comment by abrenneke** [comment]
Fixed in #189, we'll save the full refactor for later...
