### ISSUE TITLE
[Feature]: Streaming of chat node output

### ISSUE THREAD

**Issue by CRREO** [Ironclad/rivet#185]
### Feature Request

Would it be possible to enable “streaming” of chat node output (OpenAI stream chunks)? Even just directly to Graph output or API. Would be terrific and MUCH easier than hooking onPartialOutputs. Thank you - and thank you for Rivet. Amazing. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CRREO** [comment]
Thank you. Yes, tbh, I'm not even thinking about propagating the partial stream to all following nodes. I see the clean logic of first finishing one node before proceeding to execute the next one. 
What I'd love to see is just a simple way to stream the partial answer from a given chat node to an external user frontend and other modules of our app, outside of Rivet. As it is now, when I take the chat node output through the Graph Output and connect it to our app modules, I get the chat answer in bulk, when the entire generation is completed. I saw there is a way to do streaming via onPartialOutputs, but hopefully there is an easier way. 
Just sharing my "wish" :) as I think it would be super helpful for others too. 
Thank you in any case.

**Comment by abrenneke** [comment]
@CRREO what would your ideal API look like on the `rivet-node` side?

**Comment by CRREO** [comment]
thank you. Ideal API would be something that doesn't require lots of coding. Something similar to OpenAPI, which allows us to define API specs in JSON format, receive HTTP call with arguments and then _stream_ back the answer exactly as it's received by the rivet-node. Happy to connect you to my engineering colleague to help with a more technical answer. 
As a less techy user, I figured out how to do pretty much anything in Rivet, but getting a "streamed" answer from the node and outside of Rivet and to our frontend is more complicated.

**Comment by abrenneke** [comment]
I think the simplified streaming via `getProcessorEvents` and `getProcessorSSEStream` help in this regard. https://github.com/Ironclad/rivet/blob/main/packages/core/src/api/streaming.ts
