### ISSUE TITLE
[Bug]: Why did you check-in the whole .yarn cache repo?

### ISSUE THREAD

**Issue by melroy89** [Ironclad/rivet#188]
### What happened?

You checked-in the whole `.yarn` repo in git...

I _also_ see very big binary checked in in git under `packages/app/sidecars/pnpm` folder. Please, don't. Only check-in source code.

### What was the expected functionality?

Do not check in all these big files and binaries.

### Describe your environment

Linux, but that doesn't matter.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Sorry, but this is intentional, it's called yarn zero-install, and the binary checked in is on purpose too. If you need a smaller clone, you can do a blob less clone like the documentation recommends.

**Comment by melroy89** [comment]
I see.. I never really liked zero-install I think. But I think I understand your decision. Yea it's great that it's MIT licensed, I do admire that.
