### ISSUE TITLE
[Bug]: Code node inputs and outputs don't work as expected

### ISSUE THREAD

**Issue by sohilnandu** [Ironclad/rivet#195]
### What happened?

The comments in the code block say `Return an object with named outputs that match the output names specified in the node's config.` However, there is nowhere in the node config to specify the output names.

It is also unclear how to specify additional inputs into the code node. I tried using the javascript `inputs` object with no success.

### What was the expected functionality?

I expected additional input and output ports to be added to the node.

### Describe your environment

MacOS 13.4.1
Rivet IDE v1.4.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Yeah I kind of never finished the code node and now it's stuck in a kind of limbo!

Right now, it's limited to one input and one output. You get the input using `inputs.input` (`inputs.input.value` / `inputs.input.type`), and you return the output by returning 

```js
return {
  output: {
    type: 'etc',
    value: 'etc',
  }
}
```

Definitely need to fix the docs, sorry about that!

**Comment by sohilnandu** [comment]
Ah, ok. Thanks @abrenneke!
