### ISSUE TITLE
[Feature]: Option to use js-tiktoken to make deployment bundling easier

### ISSUE THREAD

**Issue by kyen99** [Ironclad/rivet#196]
### Feature Request

Rivet is an awesome tool. But, I've struggled to get it to bundle and deploy in a Next.js app to Vercel and to AWS via sst.dev.

I've tried at least 10 different hacks to deploy a simple app using rivet-node but have not yet succeeded. 

This is ultimately going to be a barrier to people to use Rivet if they can't easily deploy it to common providers. One thing that might make this easier is to provide an option for rivet-core to use, js-tiktoken, instead of @dqbd/tiktoken, which I believe should bundle and deploy seamlessly. @dqbd is recommending people use js-tiktoken when they run into bundling issues with the wasm files (e.g. https://github.com/dqbd/tiktoken/issues/61).

I still haven't been able to deploy rivet-node to either Vercel or AWS (via sst) so am also open to suggestions. I'm happy to provide an example repo with full instructions to replicate the issue as well as a list of all the things I've tried.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Yeah, tiktoken has caused me problems with bundling too, definitely. I support this! I have tried `gpt-tokenizer` and noticed it's like, orders of magnitude slower than tiktoken, unfortunately. Not sure about js-tiktoken. But it would make a lot of things simpler in the building, that's for sure.

**Comment by kojikeneda** [comment]
We may want to relate these two issues #196 and #64

**Comment by abrenneke** [comment]
Switched to using `gpt-tokenizer` in 76a74a70c9a49b7174c8bd20d063e69d239eef59 - should make bundling a lot easier with no wasm! Will be released in next minor version.

@all-contributors please add @kojikeneda for idea

**Comment by Fawwaz-2009** [comment]
hey All 👋 , I'm also struggling to get Revit to work with Next.js, I saw that @abrenneke pull request has been merged but I'm still seeing an error, is there anything that we need to change in code to switch to `gpt-tokenizer` ?, PS: I'm using the pages directory though not sure if that relevant.

![image](https://github.com/Ironclad/rivet/assets/32019791/b37186fc-1cda-4345-b26d-ffe8077bc20a)
![image](https://github.com/Ironclad/rivet/assets/32019791/07a7d71b-a5b1-4057-8828-3382ad2c5cf1)

**Comment by abrenneke** [comment]
Hey @Fawwaz-2009 I haven't published the new version that uses gpt-tokenizer quite yet

**Comment by Fawwaz-2009** [comment]
I'm leaving this here for anyone struggling to setup Rivet with Next.js. There is might be a better way but for the me the only way I managed to load the project is by putting the Rivet project in the public directory, then fetching and converting to text and use the `loadProjectFromString` loader.

![image](https://github.com/Ironclad/rivet/assets/32019791/cd5ee94b-fe95-4edb-9fbe-fb66755643d4)
