### ISSUE TITLE
[Bug]: Rivet node package runs into issues in bare Node.JS project

### ISSUE THREAD

**Issue by viveknair** [Ironclad/rivet#199]
### Situation 

I've been using the `rivet-example` repository as the basis for my testing and experimentation, which worked well to test `rivet-node` functionality. But, I recently tried to use `rivet-node` in a bare Node.JS application with only bare JavaScript files with no Typescript/Babel transpilation and no ESM (CJS only).

### Error details
I hit an exception within the bundled CJS file at `node_modules/@ironclad/rivet-core/dist/cjs/bundle.cjs` when the runtime tries to require `lodash-es` which is exclusively ESM.

The `rivet-example` repository seems to get around this issue because `ts-node` is transpiling the files in a clever way to circumvent the behavior. 🤷🏾‍♂️ I spent some time trying to understand the behavioral difference but didn't make progress.

For what it's worth, if I create a bare ESM-only Node.JS module with `"type": "module"`, it works like a charm 👌🏾

### Reproduction

I've replicated the behavior in this [CodeSandbox](https://codesandbox.io/p/sandbox/shy-http-vgjs2s).

### What was the expected functionality?

See above details

### Describe your environment

MacOS, Node 18.16.0

### Relevant screenshots

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /workspace/node_modules/lodash-es/lodash.js from /workspace/node_modules/@ironclad/rivet-core/dist/cjs/bundle.cjs not supported.
Instead change the require of lodash.js in /workspace/node_modules/@ironclad/rivet-core/dist/cjs/bundle.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/workspace/node_modules/@ironclad/rivet-core/dist/cjs/bundle.cjs:723:24)
    at Object.<anonymous> (/workspace/node_modules/@ironclad/rivet-node/dist/cjs/bundle.cjs:48:25)
    at Object.<anonymous> (/workspace/index.js:2:17) {
  code: 'ERR_REQUIRE_ESM'
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Hmm thanks for reporting. The thing is, `lodash-es` is supposed to be bundled into the final packages, and not required at all! That way, there's no ESM requires. It's definitely not `ts-node` or `tsc` doing the changes, it should be just esbuild.

**Comment by abrenneke** [comment]
Alright! Can you try 1.9.1? I fixed the aliasing of the modules in esbuild, so it should just load `lodash` now instead of `lodash-es`

@all-contributors please add @viveknair for bug

**Comment by viveknair** [comment]
@abrenneke works like a charm! 🎉 

That was the last piece of the puzzle. Now I can write some documentation for our Rivet production observability library (link below). It wraps and records the Rivet graph execution and pushes it to Gentrace.

https://www.npmjs.com/package/@gentrace/rivet-node

I know that @jasper-cooper (think I got the right handle?) from the Rivet Discord was asking about this.
