### ISSUE TITLE
Rivet high CPU usage

### ISSUE THREAD

**Issue by abrenneke** [Ironclad/rivet#200]
### Discussed in https://github.com/Ironclad/rivet/discussions/197

<div type='discussions-op-text'>

<sup>Originally posted by **adp60** October  7, 2023</sup>
Just updated to version 1.4 on windows and I have noticed that just opening a graph makes my CPU fan spin up. This is without even running a graph. Task manager shows CPU usage at 20% on a Core i9 9900. What could be the issue?  </div>

**Comment by vpckso** [comment]
I have same problem.
Ubuntu 22.04, "WebKitWebProces" using 100% of single core

**Comment by vpckso** [comment]
Caused by ContextMenu keep re-rendering.
Related dependencies:
ContextMenu: contexts
useContextMenuConfiguration: addMenuConfig
useContextMenuAddNodeConfiguration: uiData

**Comment by abrenneke** [comment]
Fixed in e90d292c6013fa7be5aa8015519b5a805b004cfd
