### ISSUE TITLE
[Bug]: Anthropic Claude Instant "Not Found" error

### ISSUE THREAD

**Issue by jasongill** [Ironclad/rivet#214]
### What happened?

Claude Instant support via the Anthropic plugin doesn't appear to be working. A simple graph that contains only 2 nodes - Prompt node with the user prompt "What is the capital of France?" attached to the input of a Chat (Anthropic) node set to Claude Instant will just spin the pinwheel icon for quite some time, and eventually return error `Error: Error processing ChatAnthropicNode: No chunks received. Response: {"error":{"type":"not_found_error","message":"Not found"}}`.

Changing the Chat (Anthropic) node's model to Claude v2 and making no other changes causes it to work and return data in just a few hundred milliseconds, so I believe that there's simply something wrong or not working properly with the Claude Instant endpoints.

I am using the "node" executor as it was noted that this is required for Anthropic support.

### What was the expected functionality?

Claude Instant should respond identically to Claude 2.

### Describe your environment

MacOS 14.0, Rivet IDE 1.5.0

### Relevant screenshots

Failure with Claude Instant:
![failure with claudeinstant](https://github.com/Ironclad/rivet/assets/241711/c7cc9f92-a06b-4f03-a90d-fc80f4ddc257)
Changed to Claude 2 and hit "run" again, success:
![success with claude2](https://github.com/Ironclad/rivet/assets/241711/800d678f-8c6f-4df4-9b85-ef26e0650b93)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Thanks for the report! Fixed in 08f731adf84ac75b2a94d3e29cadcc86149381f2. I admittedly never tested claude instant, lol. @all-contributors please add @jasongill for bug
