### ISSUE TITLE
[Feature]: Support Azure Cognitive Index Vector store

### ISSUE THREAD

**Issue by 0x80085** [Ironclad/rivet#218]
### Feature Request

Azure Cognitive Services can also store vectors / create indexes using a REST API. 
ref: https://learn.microsoft.com/en-us/azure/search/vector-search-overview

Are there any plans to support it ? 

Or is it feasible to add a plugin to support this vector store (e.g. like the pinecone plugin)
Is it possible to write such a plugin by myself ? (The create plugin page is empty on the website tho...)

Thanks for the great tool!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Hadn't heard of this before, should be possible! The plugin creation docs are currently here: https://github.com/abrenneke/rivet-plugin-example-python-exec

**Comment by elisasimoni** [comment]
Hi, i know it was more than 6 month ago, but did you manage to integrate azure cognitive search to rivet?

**Comment by 0x80085** [comment]
Apologies for the delayed response. I haven't continued working on this, so I'm unsure of the next steps. If there's no further action required, we could consider closing this ticket.
