### ISSUE TITLE
[Bug]: Update fail to update

### ISSUE THREAD

**Issue by 0x80085** [Ironclad/rivet#219]
### What happened?

Open rivet 1.4 

it will ask to update 

press YES update 

it will close program and start windows installer service and ask for permission

once done, it opens Rivet again

But the popup to  update appears again, so it didnt actually update to 1.5

clicking update again will loop this flow  again, seems the update func does not work

### What was the expected functionality?

Rivet is updated to latest version and ndoesnt show update pormpt anymore

### Describe your environment

windows 11

### Relevant screenshots

![image](https://github.com/Ironclad/rivet/assets/53451414/62233383-1a79-416a-a921-f38b880c8738)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Hmm thanks, you can download the latest version from the releases page manually right now. I'll try to see what's up.

**Comment by 0x80085** [comment]
Thank you!
This is really not a priority but I just wanted to log it. Thanks for the swift reply!
