### ISSUE TITLE
[Bug]: Code node: "TypeError: undefined is not an object (evaluating 'o.cost')"

### ISSUE THREAD

**Issue by dannykhen** [Ironclad/rivet#220]
### What happened?

With the code as seen in the attached project (graph `Test`), I get the error:
```
TypeError: undefined is not an object (evaluating 'o.cost')
```
I don't get it with any and all pieces of code, so I suspect there's something in my code that causes it. One suspicion is that Rivet doesn't support, or has issues with, async functions (or calling them) in a Code node, although I can't find evidence to this in the docs.

In any case, whatever piece of my code might be causing this, I nevertheless assert that the root cause might be a Rivet bug, because the evaluated code element in the error isn't in my code, and it apparently has something to do with trying to assess OpenAI cost (even though this simple example doesn't even have a Chat node).

I couldn't find the exact string `o.cost` in the Rivet source code (although I did find several invocations of `.cost`), so I'm not sure what's going on - maybe this code is being generated on the fly?
[bug-repro.zip](https://github.com/Ironclad/rivet/files/13058447/bug-repro.zip)

### What was the expected functionality?

My code should run as expected. It makes a `fetch` call out to the internet and outputs the result.
The URI given to `fetch` works in a browser and returns a JSON block.

### Describe your environment

Ubuntu on Windows Subsystem for Linux (WSL)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Hey thanks for the report @dannykhen.

Without seeing your code I won't be able to tell you what's wrong with it, but the jist is that this error means your code node is returning `undefined`, instead of an object like it should be.

> One suspicion is that Rivet doesn't support, or has issues with, async functions (or calling them) in a Code node,

Correct, the code node doesn't support `async/await` nor `require`. Unless you're interacting with external APIs (which isn't supported in a code node), there's little reason for supporting async/await. It's mentioned in the [Code Node FAQs](https://rivet.ironcladapp.com/docs/node-reference/code#faq)

> I couldn't find the exact string o.cost in the Rivet source code (although I did find several invocations of .cost), so I'm not sure what's going on - maybe this code is being generated on the fly?

Rivet tries to see if any node outputs a `cost` field, to see if that cost should be added to the total run cost. It's just a symptom of a node returning `undefined` for its outputs, instead of an object containing output values.

**Comment by dannykhen** [comment]
You're welcome to look at my code - I attached it to this report (in a zip file).

Yes, I was trying to use an external API, using `fetch`, which requires an async function. I now understand it's not supported.

The reason I tried that is that the HTTP node is also failing on me... that's the first node I tried to use, and even with very simple, constant URLs, it gives me `TypeError: Load failed`. So I am not sure how to proceed.

Can you please provide an example of using the HTTP node with GET and a URL input? The documentation only shows a fixed URL with no input. Maybe I'm doing something wrong here.

**Comment by abrenneke** [comment]
Try the node executor in the top right menu. The HTTP Call node will commonly run into CORS issues when accessing external APIs. I should try adding a better error message for it.

**Comment by dannykhen** [comment]
Thank you. When I choose the Node executor, the Run button disappears, and Ctrl+Return doesn't work either. How do I run the graph?

**Comment by abrenneke** [comment]
That means it's not starting correctly for some reason (which is why it's not the default, it's still kind of unstable) - try restarting Rivet maybe? You're on the latest version?

**Comment by dannykhen** [comment]
Restarting didn't help.
I grabbed v1.5.2 - same behavior.
Are there any dependencies not included in the appImage?

**Comment by abrenneke** [comment]
Nope. Must be a linux bug. I don't have a system to test on though.

**Comment by dannykhen** [comment]
Good call. I ran the same http node in Rivet on Windows and it runs correctly. I am closing this issue. Thanks!
