### ISSUE TITLE
[Feature]: Customizable user input modal window

### ISSUE THREAD

**Issue by blightbow** [Ironclad/rivet#221]
### Feature Request

Per my Discord chat with Andy, it sounds like the `user input` node is currently hardcoded to use a markdown renderer. This doesn't render cleanly when using a multi-line string as input. The preview pane for the nodes leading up to the question will all render correctly, but the modal window rendered for the actual user question will join all of the newlines together. (i.e. HTML treatment)

Ideally the `user input` node needs modal rendering settings that can be toggled. As an added bonus, this would also set you up for a potential future enhancement can pretty-print formatted text. (JSON, YAML, etc.)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Added in 6407ba27a038dc25103c52dc2ebf6728f68df14c!
