### ISSUE TITLE
[Bug]: Test Cases can't be scrolled on macOS

### ISSUE THREAD

**Issue by andriydruk** [Ironclad/rivet#222]
### What happened?

Steps:
1. Create a new project
2. Open the Trivet Test tab
3. Create a new Test Suite
4. Add new test cases (continue till the end of the window)
5. Try to scroll

### What was the expected functionality?

Scroll work for test cases

### Describe your environment

Rivet IDE v1.5.2: [Rivet_1.5.2_universal.dmg](https://github.com/Ironclad/rivet/releases/download/app-v1.5.2/Rivet_1.5.2_universal.dmg)
MacOS 12.6

### Relevant screenshots

![CleanShot 2023-10-23 at 12 39 39](https://github.com/Ironclad/rivet/assets/1927559/0493e322-667e-4466-ac73-628c0dd759a9)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Thanks! Fixed in 617a57cc06fc96e1afb0d899fc120b26504eedfc

@all-contributors please add @andriydruk for bug
