### ISSUE TITLE
[Feature]: Map nodes for arrays

### ISSUE THREAD

**Issue by a-rothwell** [Ironclad/rivet#223]
### Feature Request

It would be nice to have a map node that works on arrays to allow for an easy way to setup iterating over an array.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
A split If node is basically a map node - how do you propose the map would work?

**Comment by abrenneke** [comment]
If you have any ideas feel free to reopen!
