### ISSUE TITLE
[Feature]: Access new GPT 4 model?

### ISSUE THREAD

**Issue by crapthings** [Ironclad/rivet#234]
### Feature Request

<img width="897" alt="image" src="https://github.com/Ironclad/rivet/assets/1147704/c336f5b9-0ba1-499b-a899-00bf1be3879a">

<img width="265" alt="image" src="https://github.com/Ironclad/rivet/assets/1147704/a9becf3e-3bcd-4cbc-958b-46cd1f6403ba">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codemile** [comment]
This should be a configurable feature so it doesn't require an update to add new models.

**Comment by abrenneke** [comment]
Available now in 1.7! You can always use the `Custom Model` option in the editor to set the model to any other string.
