### ISSUE TITLE
[Bug]: Chroma plugin install fails

### ISSUE THREAD

**Issue by Michspirit99** [Ironclad/rivet#239]
### What happened?

When installing the ChromaDB plugin on a fresh install, the plugin fails to install due to plugin not being found on NPM:

### What was the expected functionality?

Plugin should successfully install

### Describe your environment

Windows 11

### Relevant screenshots

![image](https://github.com/Ironclad/rivet/assets/11279621/b164be38-9668-483c-9df0-a145f3eff238)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Oops I didn't publish it, should be good now!
