### ISSUE TITLE
[Bug]: Opening a new project fails to load with `p.fsPath.split` error

### ISSUE THREAD

**Issue by gogwilt** [Ironclad/rivet#241]
### What happened?

When opening a project, the project failed to load with an error message.

Specific steps:
1. Close all open projects, so that the "New Rivet Project" modal appears.
2. Don't fill out anything, just click "Create Project"
3. Try to open another project.

### What was the expected functionality?

Rivet should have opened the project.

### Describe your environment

MacOS, Node 20.4.0

### Relevant screenshots

<img width="1187" alt="Screenshot 2023-11-23 at 7 38 58 AM" src="https://github.com/Ironclad/rivet/assets/448108/6e5c4a1f-6a2c-4cbe-987e-e4c7711a6a54">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gogwilt** [comment]
Other reports of this happening from Discord (with a clearly different repro):

> I get this error all the time, in latest version, and last couple versions. is a bit mysterious, but is also always resolved if i closed all current projects, make a new untitled project and don't save it. then close rivet all together, then reopen, and then try to reopen the project that gave the error (sometimes 1 or 2 times for the last step, or all the steps). Fortunately it has never been a catastrophic issue. just some bug that egts cleared out with enough "unplug it and plug it back in again" sort of troubleshooting.
some common co-occurrences that might be the culprit are having multiple rivet projects open at once (especially when one is super duper big and slow to load like the rivet docs analyzer Andy made), and also seems to always happen to after i do a "save as" and then try and reopen the original file.
but idk what's actually going on...

**Comment by gogwilt** [comment]
I think the issue is in `useSyncCurrentStateIntoOpenedProjects.ts`

A lot of the effects `setOpenedProjects`. For example, there is one that adds `currentProject` to opened projects. I suspect that there are situations where you close the current project, and it somehow decides to re-add the closed project to `openProjects`, but not to the `openProjectsSortedIds` list, resulting in the project being "open," but not showing up in the project bar.

**Comment by vpckso** [comment]
Seems cause by open 2 projects, close 1 project, that closed project still exists in "openedProjects" but removed "fsPath" property.
![image](https://github.com/Ironclad/rivet/assets/40294053/3e6b92f6-b497-4ed1-8079-84c3d876979c)

If close all projects, openedProjects will becomes empty.
So, a temporary workaround is to close all projects, then open again.

**Comment by abrenneke** [comment]
Fixed in #293
