### ISSUE TITLE
[Bug]: Cannot create object with properties "type" and "value"

### ISSUE THREAD

**Issue by vpckso** [Ironclad/rivet#244]
### What happened?

When an object have "type" and "value" properties, it'll throw error "Invalid value"

### What was the expected functionality?

Rivet did not work as expected!

### Describe your environment

Ubuntu Linux

### Relevant log output

```shell
ERROR: INVALID VALUE:
{
  "type": "object",
  "value": {
    "type": 1,
    "value": 2
  }
}
```

### Relevant screenshots

![rivet_object](https://github.com/Ironclad/rivet/assets/40294053/2aec0b8d-3337-4737-8617-c2e108422aba)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codemile** [comment]
I can reproduce using the `code` node. Strangely the stringify version of the input appears to be valid JSON. I wonder if Rivet is somehow using a proxy for JSON parse and there is some kind of mutation bug.

![image](https://github.com/Ironclad/rivet/assets/50146659/4bca5e2b-9505-42b5-88be-eacac6831b8b)

**Comment by abrenneke** [comment]
Ah yeah, I added this as a safeguard so that nested types wouldn't accidentally get created. That code can probably be removed now.
