### ISSUE TITLE
[Bug]: signal.addEventListener() causing memory leaks in NodeJs

### ISSUE THREAD

**Issue by codemile** [Ironclad/rivet#253]
### What happened?

I don't have the exact steps to reproduce just yet, but I receive a "Possible EventTarget memory leak detected" warning from NodeJs when running some projects. I have one project that produces this warning when ever it runs a subgraph.

It's a pretty simple warning, NodeJs has a limit on the number of listeners that can subscribe to an abort signal. If you exceed that then you get this warning.

![image](https://github.com/Ironclad/rivet/assets/50146659/5d52592b-5be9-4c4a-808e-c4096f34d4c4)

This warning produced a stack trace to this `addEventListener` inside the bundle used by NestJs.

```
  async #processNodeWithInputData(node, inputValues, index, processId, partialOutput) {
    const instance = this.#nodeInstances[node.id];
    const nodeAbortController = this.#newAbortController();
    this.#nodeAbortControllers.set(`${node.id}-${processId}`, nodeAbortController);
    this.#abortController.signal.addEventListener("abort", () => {
      nodeAbortController.abort();
    });
    const plugin = this.#registry.getPluginFor(node.type);
    let tokenizer = this.#context.tokenizer;
    if (!tokenizer) {
      tokenizer = new GptTokenizerTokenizer();
      tokenizer.on("error", (e) => this.#emitter.emit("error", { error: e }));
    }
```

I did a quick search of the Rivet code and found 9 occurrences of adding listeners.

![image](https://github.com/Ironclad/rivet/assets/50146659/f02a0d39-1caa-425a-8d49-915c1200ea1f)

I believe to resolve this issue the code needs to be updated to call `AbortSignal.removeEventListener(...)` at the appropriate time. The callback passed for `addEventListener` needs to be used to remove it later.

### What was the expected functionality?

Should be able to run projects without triggering the limit on listeners.

### Describe your environment

Windows 11, Node v20.9.0

In addition, I'm running Rivet inside a NestJs project as part of my backend APIs. NestJs 10.2.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codemile** [comment]
I doubt the code needs to remove the listener in all cases. There is probably a function or something that is called multiple times that keeps adding listeners. There are only 9. I would guess it's just 1 of them that is the issue.

**Comment by abrenneke** [comment]
@codemile I do attempt to increase this limit in `rivet-node` by calling `events.setMaxListeners`, but it seems like that might not be working, too.

**Comment by hadoan** [comment]
Hey folks — ran into a similar memory issue recently.

I’m working on a free tool that helps analyze heap snapshots (Node, Python, .NET, etc.) and spot leaks like this one.

Just wanted to share in case it’s helpful for others debugging similar problems.

Happy to chat or give early access if anyone’s interested!
