### ISSUE TITLE
[Bug]: Global hot keys on Windows do not work

### ISSUE THREAD

**Issue by codemile** [Ironclad/rivet#261]
### What happened?

Hot keys such as "Ctrl+S" don't work on Windows. Investigated the issue down to Tauri, and looked at the Rust code in `main.rs` where the top menu is configured. Can confirm that hot keys are working on Mac as expected.

Found this relevant open issue on Tauri that hotkey support is known to be broken on Windows.

https://github.com/tauri-apps/wry/issues/451

Issue has been open since 2021, I don't think a fix is coming soon.

There aren't a lot of global hot keys being used. A possible work around would be a DOM listener just for Windows that mimics menu triggers.

### What was the expected functionality?

Pressing "Ctrl + S" should save the project.

### Describe your environment

Windows 11, Node 20.4.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Good find! Pretty lame that such a simple thing doesn't work on windows...
