### ISSUE TITLE
[Feature]: Double click a subgraph node to "Go to" that graph

### ISSUE THREAD

**Issue by codemile** [Ironclad/rivet#275]
### Feature Request

A simple quality of life feature, double clicking a subgraph node could open that subgraph.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Double click right now opens the editor for a node, do you suggest that it would behave differently for a subgraph node?

**Comment by codemile** [comment]
I suspect double click isn't working on Windows. Let me see if I can fix it first before changing the behavior.
