### ISSUE TITLE
[Bug]: Rivet page needs to be refreshed if left running for long period.

### ISSUE THREAD

**Issue by codemile** [Ironclad/rivet#278]
### What happened?

Rivet shows "Page is having a problem" after running for awhile. I don't have exact steps to reproduce, but have seen this happen on a canvas with just a few text nodes and nothing else.

### What was the expected functionality?

Rivet should run for long periods without issue.

### Describe your environment

Windows, Node 20.10.0

### Relevant screenshots

![image](https://github.com/Ironclad/rivet/assets/50146659/6ec4958f-df9c-4db1-aaa8-6e9e2fc8dbb7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codemile** [comment]
Here is memory usage on Windows. Just running a Rivet with an empty project and I'm not doing anything else, and memory usage is increasing at a constant rate. About 100mb per minute. This will be my steps to reproduce and I assume if I can stop the memory increasing then I've fixed the bug.


https://github.com/Ironclad/rivet/assets/50146659/ad193e1b-dccb-4761-9524-3adf090caea9

**Comment by codemile** [comment]
Appears to be a `WebView2` related bug and I noticed (without knowing why) if you resize the Rivet window it releases the memory. Did some digging and it seems `WebView2` has a 2GB limit so it doesn't matter how much Ram your PC has. I couldn't find any docs yet on reconfiguring the mem limit for `WbeVIew2`. I know it's not a fix but still would be nice to change it.

**Comment by mindplay-dk** [comment]
> if you resize the Rivet window it releases the memory.

this definitely sounds like a bug in the library - you should probably try to isolate the issue and report it?

**Comment by abrenneke** [comment]
Fixed in e90d292c6013fa7be5aa8015519b5a805b004cfd
