### ISSUE TITLE
[Bug]: out of memory problems

### ISSUE THREAD

**Issue by mindplay-dk** [Ironclad/rivet#286]
### What happened?

I get out of memory errors like this regularly:

![image](https://github.com/Ironclad/rivet/assets/103348/07845555-bce1-4ac8-80b5-7aeebb947ef7)

### What was the expected functionality?

not that :-)

### Describe your environment

I'm on Windows 11 Pro, all system updates installed - just playing around with Rivet 1.7.4, which I downloaded and installed today, and I've only done some very basic experiments with some text template nodes and the HTTP call node. I've only run them a few times. Errors like this occur every 20-30 minutes or so.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mindplay-dk** [comment]
I'm using the default Browser executor, haven't changed any settings (other than OpenAI key) or enabled any plugins.

**Comment by codemile** [comment]
Duplicate of #278

I'm hoping to add `e2e` tests using Selenium for Tauri that can reproduce this bug so it can be fixed. I'm thinking it's a listener subscription problem.

**Comment by mindplay-dk** [comment]
Definitely duplicate, yes - I will close this and subscribe to the other issue, thanks. :-)
