### ISSUE TITLE
[Bug]: HTTP Call: missing URL validation

### ISSUE THREAD

**Issue by mindplay-dk** [Ironclad/rivet#289]
### What happened?

If you put a relative URL such as `/something` in the URL input of the HTTP Call block, apparently it makes a request to some default host-name.

### What was the expected functionality?

Invalid URL should yield an error.

### Describe your environment

Win 11 (Browser executor)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codemile** [comment]
I see this as being related to #290

**Comment by mindplay-dk** [comment]
Yes, although that issue doesn't specifically address any missing validations - stuff like this isn't likely going to automatically emerge just by introducing a validation library. Some thinking and planning for each input will be required. 🙂

**Comment by abrenneke** [comment]
Fixed in 4f4d943188cf10306fafd09882b8f202a499276e
