### ISSUE TITLE
Array handling: Lift operations over arrays, have a "merge" operator, etc.

### ISSUE THREAD

**Issue by dominiccooney** [Ironclad/rivet#29]
I'm working on a practical use case: taking a saved Cody transcript and trying to "replay" it with some modifications. This is typical for our prompt development and testing; to date I do this in Python.

Inputs are JSON, and typically we want to take `params.messages` which is `[{speaker: 'human' : 'assistant', text: string}]`, modify the trailing message or two, serialize it to a prompt for Anthropic Claude, and prompt the LLM with that.

It appears the array handling capabilities of Rivet aren't up to this kind of task? It seems if Extract Object Path produces an array match, then piping this into an Extract Object Path object to select "speaker" isn't lifted over the elements in the array. That is, I can select "length" and not $\forall$.speaker or something.

Similarly for a node with multiple inputs, it would be nice to take multiple independent arrays and "zip" them with the node as a constructor.

I attempted simply rendering a prompt without any changes and even this workflow seemed involved enough that it would be nice to have recursive "boxes" that I could zoom out of and reuse as functions.

**Comment by abrenneke** [comment]
@dominiccooney I'm going to close this but feel free to reopen if you think this feature is still missing!
