### ISSUE TITLE
[Bug]: Destructure node returns strings as stringified arrays

### ISSUE THREAD

**Issue by ai-made-approachable** [Ironclad/rivet#291]
### What happened?

If I destructure an object, the strings cannot be directly passed into an object node.
See screenshot of the issue below.

Data example:
{
  "id": 0,
  "review_header": "less than a premium experience",
  "no_of_reviews": 73,
  "passenger_name": "Rajan Parrikar",
  "country_of_origin": "Iceland",
  "date": "4th September 2023",
  "is_verified": "Trip Verified",
  "detailed_review": "London Heathrow to Keflavik, Iceland in Business Class on an A321. British Airways provides an unusual Business Class experience for intra-Europe flights. The seating is similar to most airlines - middle seat vacant and little extra space - but on British Airways the Business Class cabin extends to almost half the aircraft. This makes it less than a premium experience at every step, from boarding to onboard. The WiFi worked for only half the flight and there are no refunds. But when it worked it was surprisingly fast. Service on this flight was very good and we got to Keflavik on time.",
  "rating_dict": {
    "Aircraft": "A321",
    "Type Of Traveller": "Couple Leisure",
    "Seat Type": "Business Class",
    "Route": "London to Keflavik",
    "Date Flown": "August 2023",
    "Seat Comfort": 3,
    "Cabin Staff Service": 4,
    "Food & Beverages": 3,
    "Ground Service": 4,
    "Wifi & Connectivity": 3,
    "Value For Money": 4,
    "Recommended": "yes"
  }
}

### What was the expected functionality?

Destructure node returns proper strings that can be used as input for an object node.

### Describe your environment

MacOS, Node 14.0.0, etc.

### Relevant screenshots

![image](https://github.com/Ironclad/rivet/assets/149181237/e084abd5-4869-47ec-9922-3ab521ea2f90)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Fixed in 3748f16012d0640687c1969057798b9e77499b40
