### ISSUE TITLE
[Bug]: Array from object node does not return strings properly to next node if split is active

### ISSUE THREAD

**Issue by ai-made-approachable** [Ironclad/rivet#294]
### What happened?

I have an array in an object node, e.g.
[
  "Can you suggest a good smartphone for a new purchase?",
  "I'm in the market for a new phone. Which one do you think is the best right now?"
]

If I use that as an input (e.g. for embedding node) and activate split it returns:
- "Can you suggest a good smartphone for a new purchase?"
- "I'm in the market for a new phone. Which one do you think is the best right now?"

### What was the expected functionality?

It should return:
- Can you suggest a good smartphone for a new purchase?
- I'm in the market for a new phone. Which one do you think is the best right now?

### Describe your environment

MacOS

### Relevant screenshots

![image](https://github.com/Ironclad/rivet/assets/149181237/527276ec-a805-4643-a33f-df858965f69c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Should be fixed by #321 as well
