### ISSUE TITLE
[Feature]: GPT Function Node "Description" should be a multi-line input.

### ISSUE THREAD

**Issue by gogwilt** [Ironclad/rivet#296]
### Feature Request

The GPT Function Node "Description" field is a single-line input. These descriptions can get pretty long, so it would be great for them to be a multi-line input or textarea.

Currently, I'm resorting to copying and pasting the text to a text editor, editing the text, then copy-pasting it back in.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Fixed in 72fb94c3fa2d53d38ab356848739c72e90b4c831
