### ISSUE TITLE
[Bug]: OpenAI Plugin - Tool/Function Calls

### ISSUE THREAD

**Issue by Jasper-Cooper-AutoRFP** [Ironclad/rivet#298]
### What happened?

**Tool/Function Calls are not working on the OpenAI Built-in Plugin**

When there is a function call in a thread, the thread run completed before status = complete.

**Steps to reproduce:**

1. Create an Assistant with a Function
2. Create a Thread
3. Run Thread with Function

You will receive the output before it's done, meaning that there:

A) Is no assistant response yet
B) Is an assistant response where the text.value = "" because it is yet to complete.

But in each case the status of the run !== complete and the node Run Thread Node still seems to output to early.

**Example Output that is too early:**
![image](https://github.com/Ironclad/rivet/assets/106525617/08347916-0b30-4729-8b8d-14e4cf06ae30)

**Example Graph**
I tried to upload the Graph here, but GitHub won't allow the extension so if you change this from "txt" to "rivet-graph" it hopefully imports:
[Example_of_OpenAI_Threads_Function_Call.txt](https://github.com/Ironclad/rivet/files/13823987/Example_of_OpenAI_Threads_Function_Call.txt)

### What was the expected functionality?

I expected Rivet to poll using the existing Run Thread Node code until the Run was status = complete. Meaning that there would be a response from the assistant.

Instead, depending on timing I will receive no message from the assistant or a blank response from the assistant.

When I open the same thread in OpenAI later, it has a completed status and full response from the assistant as expected. So it seems to be simply not waiting until completion. 

### Describe your environment

Windows 11 Pro 
Node v20.5.1

Replicated by other users on Discord

### Relevant screenshots

**Full Flow**
<img width="818" alt="image" src="https://github.com/Ironclad/rivet/assets/106525617/a45fa4c4-1c0b-44e0-9a45-e85f7e3fee05">

**Run Output where the status is still queued**
<img width="236" alt="image" src="https://github.com/Ironclad/rivet/assets/106525617/dc280b4a-2e50-4629-982b-cec077375c0e">

**Showing no last assistant message**
<img width="579" alt="image" src="https://github.com/Ironclad/rivet/assets/106525617/4fd0fbe8-937c-4352-8ef2-ed009a188955">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Fixed in 4e308640569d66d89facc5c34bd9bd524a0f0027
