### ISSUE TITLE
[Bug]: Split SEQUENTIAL flag lost when project files reloaded

### ISSUE THREAD

**Issue by drpriceless** [Ironclad/rivet#299]
### What happened?

When I open a file (via menu open project) where a node is set with split and sequential, the sequential option is lost.
this happens in the subgraph node and the Ollama node (those are where I have tested it)

### What was the expected functionality?

Expected function is that the sequential flag you be maintained across save / load 

### Describe your environment

MacOS 14.2.1, Rivet 1.7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Fixed in d8c09633c56224f5cdb3aacf88850e21404c2318
