### ISSUE TITLE
[Bug]: Object node breaks frontend if too much content is inserted

### ISSUE THREAD

**Issue by ai-made-approachable** [Ironclad/rivet#300]
### What happened?

Object node cannot be handled anymore if you insert this:

[
    "de4842c8-a1bc-4845-9b4b-4892684df86c", "96f307ee-71c0-4469-b224-bab8f2db0cad", "bf086348-83cd-4769-990f-dba7bc366fb5", "8361387b-48f4-440a-b7b1-e6e9b5c3b639", "4ce37e7b-735b-40e6-8d64-0af82ea03ba0", "a67e8a02-1d2f-4e54-bd43-cfffdbc0c014", "6f5c7f80-b1fd-4880-b7e6-b343b2cef927", "22627368-a82e-413a-bad5-0802abe76a5a", "33cf27c2-757c-41ae-8e11-be3d3dc9d32f", "111e87b5-b425-4ee1-9916-491ec3c9bb95", "3ddaebdf-6461-4623-8b7b-f3991eb3442b", "11e8b060-6e4c-420b-9067-ff469ce63cab", "c890fc17-efc5-4614-b3c6-22932987f4e4", "f7f09b90-a0eb-4be2-826c-6242f4ed9c94", "9c57b28e-5706-4aa6-b66f-04457570c3dd", "c9e44185-965b-4145-ac38-dea880dc5e2f", "da58f816-b401-4b3a-90c8-f9d6da731200", "c6f5cf79-cfaa-4f16-88d5-985db02df5ba", "51855dfa-1ecb-46f2-a766-cda5d9f7c3df", "c7de2368-ace9-47db-b516-26d2c924ee5e", "0a004d8d-0248-4e19-9170-318d88d07c57", "70694f12-4b94-4838-b257-2a4aac775606", "24563d81-e35c-4673-aa7c-f9832997ed0f", "7115db95-ffb4-4c85-857d-5d8c48db106e", "45ad8e78-e154-481b-8448-f61522c2ba1b", "e9eb2393-67af-4426-a535-73fe94111d12", "c7af5251-c136-473c-8b71-e1c5dee0b08d", "06194801-cb03-4b07-9226-046ef3d6eb43", "5a48b21a-a9f6-4bc4-9c45-51f7321deac6", "35468b6b-9511-43b9-953b-37c0ce720f98", "24c123f7-7ddf-4ad5-9bfc-6c6d38bba202", "09267daa-c4d0-415c-94bf-4410af024c44", "d776b707-63cd-463f-9ab0-92aabd9228b6", "33601b4e-6e90-4b72-86ec-7fd4ba4632ad", "d317dbef-5d1c-4a75-98a3-c0488114a21c", "9bd17b78-baa3-46e5-a802-73d6ea4ad15e", "6a836c39-d0ba-469b-b6d1-e522a993a61e", "e843e850-2f35-4aab-a795-327e6415f6f4", "444b3af3-9f9a-48cd-a671-1b65c55b35c9", "e990e79f-2a97-435f-b539-2bb121750002", "05a75d10-d9b2-4e5e-bc44-b8f16a5e0475", "e0402407-c11c-4476-8571-81154564f392", "d677ebdb-9814-4ee2-a016-9b9885b07bfa", "a9569ee4-6262-467c-9609-4506920df065", "caabf3d8-b410-4ee4-944a-0bcbe3ed2023", "fe0f1442-caa9-470e-ab4f-4f1a96197f9d", "54de9dfe-4601-4539-9dfc-d19d913b1c0e", "01c3c1f3-c4e3-4cda-aff8-949667962750", "3a3f38fe-7639-4af2-bd43-18cdf8819844", "ff00cadf-deda-44ac-972c-6dfc30ddc84d", "9d94f19d-2cba-4e39-ac91-c5e3a76ab67c", "c9001964-fed0-42b8-99f9-f163165bda78", "e086c0c6-b07e-4a8e-8608-9a94b8d789f9", "ba635622-7b1c-4867-8917-4134b563034c", "c66a8c49-11f7-4738-a27a-080158b68214", "4b8dae1d-13f5-4816-9e2e-76b657d2bac6", "5c3bc23e-14a2-46a7-88f7-9f4b1e728849", "a9b3107f-009e-4132-a366-bca2d27bfe49", "0c7343ba-bf09-4caf-af30-65ddc8e66459", "95f2a8e3-21e8-4950-be06-9457da91d1e9", "dbf3aa3a-0432-4c71-a592-37eb3b5cee79", "c02a7a06-2c10-4e95-a61d-e1a363fca068", "0c6fb046-10ca-4b2e-a905-fb5d3321814a", "0528cae8-6353-4ac5-8412-94aef0c5e331", "c7d6450f-1b53-4704-a545-b264e8d34757", "087e5a5d-3e36-4fad-9c8f-cdeccbd2e1c8", "3986a112-91c4-4f7a-a72f-2a03db08be6f", "1629b8f6-8e7a-44bd-9900-7e9c0323f8df", "f03bfb88-fd0a-4897-abc9-1d316749a1df", "3d2ac1cd-895c-423c-8aaa-b52619641a2d", "116ac6e6-0bc2-4857-acde-0e9386004b7a", "06dca96d-485c-4c99-8729-82b9b28365e0", "74da7817-dd22-4978-9042-17bb2804ac25", "dc9c475f-76d4-47dd-a9dc-340f6b0b83ef", "30128f2d-2882-4b81-9de4-59c52ad2edd1", "f9a40b25-c4d9-438b-88f5-6262c29eb8c9", "5b6f2626-6e5c-4acf-9fed-0ca926f90dde", "7790cf85-69cc-48a1-8b38-d25cb9b7be34", "83001e9a-c664-4996-8085-dc5163612e4c", "40402408-cd08-47a3-b454-2fc3cc1a3bd2", "c32d6000-ac07-4b35-9c89-086eaddca77a", "95063978-e189-4d07-8048-b3c90cf5b041", "0c7dd2d5-cd16-4818-8aa5-c32ba7d50159", "e9b14526-999d-494f-9a1c-8bb3dcfc1d2a", "8df27e70-f6c2-4e56-8838-d47545c7c1d0", "4d01cebb-944d-44a9-997f-37254a94145d", "1f4d2b15-7fc8-4351-a5bf-b7ff1114bc18", "45173fcb-d50b-4d41-834b-66c6e064199d", "b4d6a7a1-2a0a-4a7d-9904-19e92da21d90", "0f0faf90-109d-4e8d-962f-fb82870411a6", "edb93d25-c90e-449d-af24-e385db72850a", "4fad5ad5-c1a1-4a1c-be4b-1656e200068f", "ebd9b124-594d-4ad2-9ca5-4efcda8ea68e", "fbd31e5d-5274-46de-bac7-60e6d475d95c", "4022e8f4-cb21-42cd-809f-0c0d5b7dd477", "3026a523-98bd-49dd-86e8-69da07525dc6", "f6f545c0-46a8-4d43-91ba-80150e7accc9", "b6568459-5406-4717-b348-06fcf8b3609b", "e943f0ae-9e82-4a93-a596-99403116f019", "404e35cd-c0bb-44e6-bbb7-9d0098876b2a", "8750393a-ed34-4308-a1a9-b1065395985f", "828e8d76-a8b4-4b5b-9042-ab98a02de107", "e6a1ba9b-1351-45d9-b2f9-e8465a68836c", "546cc54c-12e2-4c7c-897b-2ec378e3183c", "72512d52-23a4-4e74-aaa8-916049413beb", "1ed6c235-7e5a-41ee-b8f2-4cb9e3f41500", "3cf97a96-6c63-4e57-827b-f90484aaa032", "54454abd-4f49-414b-b5c8-f5914d774518", "cd28883f-ffcd-4055-af68-c3a814ce0088", "8cf364fb-4eeb-40ab-a516-1fed3af47a2d", "683cbbfd-dc23-4856-b9c5-b9cee9d60754", "71257b44-5d1a-45fe-a395-6672a65d0945", "724b0c53-6f67-43ad-91d4-795bb0bd7136", "c4e05079-e07f-4e9b-939a-3780783cfa60", "da20f686-1cc4-406f-a604-1bc7723880f9", "4f82945d-fcef-4056-b8ce-5e22beee8a97", "b87d0440-c87a-4c97-89de-675d7c598bd1", "09148cdc-0529-4712-907e-40629437c041", "0ecc8d1d-fa50-4c29-9c08-87dd657d54a6", "c7232acd-0b6b-4cc5-81a9-5ce48e233acb", "bc0b6f21-c3da-436d-a3eb-7c60034ae08e", "386d3ea9-bfb3-425f-88fa-993cf574968c", "31da1fea-d7e0-494e-8923-f549da78aa5c", "62ab286a-d9e9-4a92-b26e-1b15d015fa22", "eb0e0acb-b026-45a0-9649-2f881bb7788b", "d2c4129e-f286-4d3e-94df-f2012cfb40f4", "c65381fa-6d3f-4a3c-990b-7967425a4a9b", "41532de1-e427-4d1f-bcf1-19ba2900429a", "5a0717ca-731c-47d4-a1af-37b9dd06c91f", "2f5efae8-785e-41c7-8e01-c7403bd9b865", "715c8909-d631-46ec-87e5-f23c78fbe76d", "76e14567-d2eb-4596-9bc9-bf0eb82dffaa", "5f6c97de-ef4a-44cf-aff4-4d314639f4e0", "4780bf72-f838-48a2-aebc-c189191fa2ab", "ad8ca26e-2fcd-4c9e-9a20-476f963fdb9c", "7f87ec60-dfbd-4000-a7a5-2ea158de429e", "5b4af0e1-6b03-457a-84a6-586d00e8659f", "2080df24-903c-4c4e-890d-2e6c9febeaba", "170939e1-21ab-404e-baae-497c1667913b", "c54cd0ff-50c7-413b-8962-a1d199657e47", "45577151-166c-407d-ae7d-10fb1468fb3d", "f307a7f0-3008-4df3-948c-131950a36528", "16d89398-b7c7-49f8-95dc-0360b5846702", "500fb274-22bb-4a7d-a0f9-61558e4bb65e", "ed4f7be5-35f4-436b-bc1f-d96a532c9ad2", "49251b7a-cca7-46ee-a009-7d2cc776f241", "71b33a29-5d60-4e22-b365-1e7200f24843", "3e03625e-dfe0-407c-9d1e-3b1bf73dc8cf", "5069111c-a0e3-4e0e-96f0-808c7691cc0b", "9754cbe7-28f3-4a2f-81b7-a5aa288de58c", "59cf2c6a-370a-4075-b52b-a4810e56cde5", "ca3b6e0b-7e47-4fbc-b3b8-185b05c8943b", "454cb011-249b-40e4-9057-8e9c86f55629", "36d5a0c1-ead9-4fb5-b00b-88a134ed35cd", "10be0158-dfbf-435b-b5e7-3bbdd8025bdc", "b60b2231-e1b1-469a-a05a-a92838e004ad", "f9659a13-34cf-4656-a8e2-8dac78c04a6e", "68d6bb12-2079-454c-b950-9adf8cd0f17a", "5ec98f49-f093-4972-a6c7-0999f5e7d92c", "ab80de15-a7fe-4b53-a142-0f16f3d05480", "1c647b11-ab4c-45b1-9b60-0b2230d77c7a", "78d3b42a-d157-4226-a0af-504bc35b0c9a", "65ab9dca-4d3a-4a8a-a065-90feb3253e11", "efac0fc6-3241-4062-9639-f6c8424611ab", "27b75cca-e991-43aa-b72b-a94c93aa5c00", "01df944e-b5c2-4b0d-b5a9-59b7a80ff009", "a59153cb-f3c5-4225-8728-4548124622a8", "f6e7ada8-3613-476b-b541-186085471b47", "38605762-7e33-4afe-8afd-d4bd493d3174", "0cd1dd1c-7b25-42de-bbbe-e5eae9e70a65", "559f2b10-46f2-425d-b47c-579be4150c38", "37478c16-59d2-44a0-936c-7baaac3ecfd5", "64f921e8-80c2-4398-8581-1df3e3243ac4", "2ca7eaf1-58b4-455c-aff0-8568d0760a62", "d4927089-f193-4a8e-8fee-0b95360afb42", "52d69641-ed61-454a-9786-7be4d12c5192", "7a7325f4-3e57-4253-9bad-624318d10ef0", "27d70d12-ed78-49cc-bccb-e1b9220bc781", "1d3276df-8cb7-465f-a9c6-13f8d22d2170", "dbef6198-56a7-47b6-a8f6-f41c54d3101e", "f05dfefb-aea7-436f-9032-6680655ec51c", "6c0ab7d3-ecfb-4b4f-898c-6267d87f6dcf", "0e80346f-0625-47bc-b604-597390856a96", "ae42621d-e03f-4352-82b6-3e1fb8a5b0c3", "ceca763b-6903-444b-84cc-a884cdc9c859", "021616ca-594e-4f97-9633-f18607c47a3f", "cd873c47-f48a-4d2f-8bf6-231b72a5d5f4", "2f4dc91c-03f7-4b62-8fcb-46cb3ff6a938", "af171ed4-3f82-4931-a934-d3fe9224ea97", "0df1eedf-1220-4243-8dc4-91632169022c", "821940a0-83c9-4646-bb24-8bf3463c2d0d", "2cff4869-358a-4558-8baa-e865c361ec1f", "c6fc1f98-9fed-4902-aaaa-6dbbeb4b18fd", "29593e51-5ef2-40ea-b6ce-302e15382275", "f5c1c0f7-d8a3-4598-b6a7-3114c459d826"
    ]__

### What was the expected functionality?

Object node will behave as text node and just cut off the content

### Describe your environment

MacOS, Node 14.0.0, etc.

### Relevant screenshots

![image](https://github.com/Ironclad/rivet/assets/149181237/af749b33-ca68-49ca-b187-91637f6b5130)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codemile** [comment]
I suspect this might not be an easy fix, but I'll take a look. As I think this impacts a broad way node props are displayed.
