### ISSUE TITLE
[Feature]: Support parallel function-calling for OpenAI GPT-4-turbo

### ISSUE THREAD

**Issue by gogwilt** [Ironclad/rivet#311]
### Feature Request

GPT-4-turbo now supports parallel function-calling, but the Chat Node "Function Call" output only returns a single function call. The Chat Node should support parallel function-calling.

To do this in a backwards-compatible fashion, we may want to add an option "parallel function calling," which creates a "function calls" array output (and removes the single "function call" output). Then, existing for chat nodes already using this port, the "parallel function calling" option will be false, and it will work as before.

And to make this forwards-compatible, we probably want to make parallel function calling default to "true."

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Implemented in f1b90b12184523f1850e2ed4b9e99ab00e4b8ce6, your approach is the right one!
