### ISSUE TITLE
[Bug]: Cant' open project -  undefined is not an object (evaluating 'c.fsPath.split')

### ISSUE THREAD

**Issue by Eggwise** [Ironclad/rivet#313]
### What happened?

When i want to open a project i get this error:

Failed to load project: undefined is not an object (evaluating 'c.fsPath.split')

This is annoying because i put a lot of work in the project and now i cannot load it :/

### What was the expected functionality?

Open my project

### Describe your environment

macbook pro m2,  rivet 1.7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Eggwise** [comment]
This seems to happen when i opened a project.
And try to open a clone of the project with the same ID

**Comment by codemile** [comment]
fixed by PR https://github.com/Ironclad/rivet/pull/293
