### ISSUE TITLE
[Bug]: Code node coerces array inputs into a string

### ISSUE THREAD

**Issue by hotelbuddy-online** [Ironclad/rivet#317]
### What happened?

when using code node, it seems to change the type of the input when it is an array. a workaround is to convert into an object which is an array, but this seems irregular

### What was the expected functionality?

the input node should have same data type as what goes into it.  

### Describe your environment

MacOS, Node 14.0.0, etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
@hotelbuddy-online could you give more info about the input you're providing to the code node? It doesn't intentionally change the input type to anything in particular (no coercion), can you provide a minimal reproduction?

**Comment by abrenneke** [comment]
feel free to reopen if you have more info
