### ISSUE TITLE
[Feature]: Create a "reroute" node for cleaner graphs

### ISSUE THREAD

**Issue by ai-made-approachable** [Ironclad/rivet#328]
### Feature Request

ComfyUI has a reroute node which is used to able to reroute the connections between nodes to make the graph cleaner/improve readability. I think this is pretty cool.

https://blenderneko.github.io/ComfyUI-docs/Interface/UtilityNodes/#reroute

Example image (reroute node used at the top)
![image](https://github.com/Ironclad/rivet/assets/149181237/0280caae-2088-49fe-901a-a47a74263e7d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
That's what the Passthrough node is for!

**Comment by ai-made-approachable** [comment]
Wow. I never saw that node ;) Okay, closed.
