### ISSUE TITLE
[Bug]: "Render markdown" in chat nodes output is not working

### ISSUE THREAD

**Issue by ai-made-approachable** [Ironclad/rivet#329]
### What happened?

If I activate "render markdown" for the chat node it does not render markdown (see screenshot)

### What was the expected functionality?

The option renders markdown.

### Describe your environment

MacOS, Node 14.0.0, etc.

### Relevant screenshots

<img width="1440" alt="image" src="https://github.com/Ironclad/rivet/assets/149181237/059dc3e1-15ae-4124-ba70-c152af1c02fb">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
It's working for me, can you give a more detailed reproduction? 
![Uploading image.png…]()

**Comment by ai-made-approachable** [comment]
I can also not immediately reproduce it with the chat node, but found another case that is reproducable. If you look at the output of a subgraph it does not work.

Just run the main graph and look at the output of the subgraph and activate the "render markdown".

Cannot upload the rivet file, so here is its content:

version: 4
data:
  attachedData:
    trivet:
      testSuites: []
      version: 1
  graphs:
    P_AiOxntuyLf5Md9wWqsz:
      metadata:
        description: ""
        id: P_AiOxntuyLf5Md9wWqsz
        name: Main Graph
      nodes:
        '[61Um3XcTFZFIvIhsC3R5J]:subGraph "Subgraph"':
          data:
            graphId: PwirGz1O1AzPu5oSEORU-
            useAsGraphPartialOutput: false
            useErrorOutput: false
          visualData: 409/286/330/2//
    PwirGz1O1AzPu5oSEORU-:
      metadata:
        description: ""
        id: PwirGz1O1AzPu5oSEORU-
        name: Subgraph
      nodes:
        '[X6BlTlZPq9Isnu2lXm-oj]:text "Text"':
          data:
            text: Render some markdown for testing
          outgoingConnections:
            - output->"Chat" k6n76N25xjy2_lBRKWLQh/prompt
          visualData: 351/328/330/2//
        '[ixkEPDUqMUG-EmiqWHWNC]:graphOutput "Graph Output"':
          data:
            dataType: string
            id: output
          visualData: 1202/315/330/4//
        '[k6n76N25xjy2_lBRKWLQh]:chat "Chat"':
          data:
            cache: false
            enableFunctionUse: false
            frequencyPenalty: 0
            maxTokens: 1024
            model: gpt-3.5-turbo
            parallelFunctionCalling: true
            presencePenalty: 0
            stop: ""
            temperature: 0.5
            top_p: 1
            useAsGraphPartialOutput: true
            useFrequencyPenaltyInput: false
            useMaxTokensInput: false
            useModelInput: false
            usePresencePenaltyInput: false
            useStop: false
            useStopInput: false
            useTemperatureInput: false
            useTopP: false
            useTopPInput: false
            useUseTopPInput: false
            useUserInput: false
          outgoingConnections:
            - response->"Graph Output" ixkEPDUqMUG-EmiqWHWNC/value
          visualData: 794/258/230/3//
  metadata:
    description: ""
    id: 5ec1QuhLogc1rLeH6DEiy
    title: Markdown issue
  plugins: []

**Comment by abrenneke** [comment]
Fixed subgraph nodes in 1e340da66b7ddecee2cd9829f834f183eee112e5
