### ISSUE TITLE
[Bug]: Anthropic Plugin not working ("undefined" error on Chat node)

### ISSUE THREAD

**Issue by wayne-chang** [Ironclad/rivet#332]
### What happened?

<img width="1183" alt="image" src="https://github.com/Ironclad/rivet/assets/969364/797408a8-3c78-425b-803f-554342e1ae6a">

### What was the expected functionality?

Expected Claude 2.1 to execute but getting "undefined" error on the Max Tokens.

### Describe your environment

Mac OS, Node v21.5.0, Anthropic Plugin

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gogwilt** [comment]
I think the Claude chat node tries to enforce token limits, and does this with a dictionary mapping model names to token limits. We need to cover the case where the model is unknown, in which case we cannot enforce token limits that are unknown.

Should be a simple fix.

**Comment by abrenneke** [comment]
Fixed in 4055482bf1f4ad2a598df909ff14d95c39bce5dc
