### ISSUE TITLE
[Feature]: "Upload File to OpenAI" node needs filename input

### ISSUE THREAD

**Issue by ai-made-approachable** [Ironclad/rivet#335]
### Feature Request

Please add a filename input. If you want to use the files in the assistants API the assistant often has issues reading the file, as it does not know what kind of file it is. Sometimes it tries to test if the file is in binary and succeed. But that is sometimes.

To make this smooth in Rivet, the "Read File" node should probably also return the filename as an output, so that you can connect both immediately.

Here is how uploaded files look:
<img width="375" alt="image" src="https://github.com/Ironclad/rivet/assets/149181237/f84eab0c-bc4f-424e-ac97-38fb3fb710b2">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Added in 08846b835f538b528f0326d411f9e958be51f368
