### ISSUE TITLE
[Bug]: "Run Thread" node overwrites functions assigend to the assistant

### ISSUE THREAD

**Issue by ai-made-approachable** [Ironclad/rivet#336]
### What happened?

If I assign functions to the assistant and use "Run Thread" node without reattaching the functions/tools, they are not available.

### What was the expected functionality?

If funtions are configured for the assistant, they shall NOT be overwritten by the "Run Thread" node if there is no functions input connected

### Describe your environment

MacOS, Node 14.0.0, etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Fixed in 1b534f8eb6c8454d3ad33296104b910bd3c1e162
