### ISSUE TITLE
[Bug]: Wrong selection in "Upload File to OpenAI"

### ISSUE THREAD

**Issue by ai-made-approachable** [Ironclad/rivet#339]
### What happened?

You can select "Fine Tuning Results" but that does not exist.

### What was the expected functionality?

Remove selection that is not supported

### Describe your environment

MacOS, Node 14.0.0, etc.

### Relevant screenshots

<img width="309" alt="image" src="https://github.com/Ironclad/rivet/assets/149181237/3463a114-0d88-48aa-8dd4-ccf002ae12fe">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Fixed in 51a57d4a56724595d7740ebee07cd0d8cb33a8ba
