### ISSUE TITLE
[Feature]: How to build binary file with cross platform？

### ISSUE THREAD

**Issue by yk133** [Ironclad/rivet#341]
### Feature Request

How to build binary file with cross platform？
In ubuntu，How to build Windows platform binary? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Sorry I don't quite understand the question, are you asking how to compile Rivet for Windows, on Ubuntu?

**Comment by yk133** [comment]
@abrenneke  yes

**Comment by abrenneke** [comment]
Unfortunately that's not possible. You need a windows machine to build Rivet for Windows.
