### ISSUE TITLE
[Feature]: Chroma Update node requires Embeddings to update the metadata

### ISSUE THREAD

**Issue by igor2c** [Ironclad/rivet#352]
### Feature Request

In Chroma plugin, is should be possible to update the metadata without remaking the embeddings from scratch.

The Chroma Update node currently requires Embeddings input: https://github.com/abrenneke/rivet-plugin-chromadb?tab=readme-ov-file#chroma-update

However, Embeddings are optional on the Chroma side.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Done in chroma plugin 0.2.0!
