### ISSUE TITLE
[Feature]: Add AI generation to regex node as well

### ISSUE THREAD

**Issue by ai-made-approachable** [Ironclad/rivet#354]
### Feature Request

Same as code node regex node is a bit complicated for many users and ChatGPT also often generates regex that cannot directly be used. So it would be great if we had some "ask ChatGPT" feature there as well which automatically adds the neccesary instructions.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Good idea!

**Comment by abrenneke** [comment]
Done in 137c3a49682aed22d1590bd4ba5ba7f8425474bf!
