### ISSUE TITLE
[Bug]: inconsistent behavior in "Extract JSON"

### ISSUE THREAD

**Issue by mindplay-dk** [Ironclad/rivet#362]
### What happened?

It fails to parse fenced JSON arrays:

![image](https://github.com/Ironclad/rivet/assets/103348/76aec515-cd1c-409d-90a2-2941c211dc62)

Here's a minimal repro:

[json-issue.zip](https://github.com/Ironclad/rivet/files/14405945/json-issue.zip)

### What was the expected functionality?

It should work consistently with any valid JSON value, including arrays.

### Describe your environment

Win 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Fixed in 6a1b78fe846821349ae9684b29fed5b2b93393b9
