### ISSUE TITLE
[Feature]: More Ollama support with nomic embeddings.

### ISSUE THREAD

**Issue by Mayorc1978** [Ironclad/rivet#370]
### Feature Request

To increase the potential of usage of Rivet using local LLMs, please increase the support for Ollama including support for bert and nomic embeddings.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Can you explain what you mean more? The Ollama plugin for Rivet supports generating embeddings.
