### ISSUE TITLE
[Bug]: Plugins working on MacOS or Windows(not confirmed) are not on Ubuntu Jammy

### ISSUE THREAD

**Issue by al-sabr** [Ironclad/rivet#371]
### What happened?

See conversation link on discord : https://discord.com/channels/1149376303070466110/1170882289417343016/1215619223745863690

### What was the expected functionality?

Node running without showing an error

### Describe your environment

Ubuntu Jammy, node 18

### Relevant log output

```
Error: Cannot find module 'node-html-markdown' Require stack: - /home/dumbo/.local/share/com.ironcladapp.rivet/plugins/rivet-plugin-html2md-latest/package/dist/nodeEntry.cjs 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
I would open an issue in that project, because this isn't specific to Ubuntu.
