### ISSUE TITLE
[Feature]: Ability to pass to image node the response body of an http call

### ISSUE THREAD

**Issue by andris1** [Ironclad/rivet#386]
### Feature Request

![image](https://github.com/Ironclad/rivet/assets/7359842/f2ae72bf-0fda-44dc-9100-73bb977036c9)
In a scenario like this, where I'm requesting an image with an http call node, it would be nice if I could pass the response body directly to the image node.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by liaujianjie** [comment]
I'll be happy to put a PR up for this feature if the maintainer team could provide some guidance on how to approach this. 😄
