### ISSUE TITLE
[Bug]: This node can only be run using a nodejs executor

### ISSUE THREAD

**Issue by everythingability** [Ironclad/rivet#395]
### What happened?

A bug happened! Or maybe a feature... 

### What was the expected functionality?

I added the FS plugin and tried to write some data to file. The path and filename were hard-coded.

### Describe your environment

MacOS, latest Rivet

### Relevant log output

```shell
Error: This node can only be run using a nodejs executor.
```

### Relevant screenshots

<img width="934" alt="image" src="https://github.com/Ironclad/rivet/assets/96276/cfc37a00-edbb-4bdb-bde1-cd25f6b1570e">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffhaskin** [comment]
This exact scenario happened to me as well just now, except on windows 10. Hard-coded path and filename. Same error.

**Comment by abrenneke** [comment]
Yeah, in the cog menu, switch the executor to Node and this should work.

**Comment by eric-burel** [comment]
The "run" button disappears when switching to Node executor, what could explain that?
