### ISSUE TITLE
[Feature]: Mulit-LLM support

### ISSUE THREAD

**Issue by ccollie** [Ironclad/rivet#414]
### Feature Request

What would it take to have multi-llm support ? I'm working on a SAAS product where we allow the end-user to choose between various providers (for cost, fit and latency reasons), so for us this feature is important. I may have some resources available to devote to this if it's attainable with not too much of a lift.

 Is there an interface that the OpenAI integration uses that is sufficiently general to be a basis for other implementations ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kucukkanat** [comment]
I am not quite sure what you mean by multi-llm support but Rivet already supports Ollama, OpenAI, Anthropic and (all) HuggingFace compatible models via their built-in plugins you can install with one click. 
You are also able to provide the model to the node via a text node which can come from the Graph Input that you plug in to your API, so when a user picks a model you use that as an input to your LLM node.

**Comment by abrenneke** [comment]
Yeah what kucukkant said
