### ISSUE TITLE
[Feature]: GPT-4o?

### ISSUE THREAD

**Issue by VikFinlay** [Ironclad/rivet#419]
### Feature Request

Hi,
am I wrong or GPT-4o is not supported?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lucas** [comment]
This was already done, just waiting for the next release: https://github.com/Ironclad/rivet/pull/412

**Comment by abrenneke** [comment]
Also, you can use it right now by putting `gpt-4o` in the "Custom Model" field under "Advanced".

**Comment by abrenneke** [comment]
Closing because the next version will have this, and `gpt-4o-mini` as the new default
