### ISSUE TITLE
[Feature]:   Integration of Azure AI Search Plugin

### ISSUE THREAD

**Issue by elisasimoni** [Ironclad/rivet#421]
### Feature Request

I would like to request, if it is possibile, the addition of a new feature to Rivet that allows for the integration of Azure AI Search as a plugin. This feature would enable Rivet users to leverage the powerful search capabilities of Azure AI directly within the Rivet interface.

Are there any plans to support it? It's already present? 
 
 it will be very helpful and integrated with most of the other tool already supported.
 
 Thanks in advance

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Thanks for the suggestion! This is a good idea for a plugin - nothing is planned right now, but maybe someone will step up and write a plugin!
