### ISSUE TITLE
[Feature]: image input for Anthropic plugin

### ISSUE THREAD

**Issue by liaujianjie** [Ironclad/rivet#429]
### Feature Request

We are able to pass an image URL into an assemble node. That assemble node can be passed and successfully run on the OpenAI Chat node. However, this cannot be done for the Anthropic chat node.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Hey @liaujianjie you can do it like this:

![image](https://github.com/user-attachments/assets/c8ba1618-cbc3-4532-a16f-029127d90d10)
