### ISSUE TITLE
[Feature]: async code support for code block

### ISSUE THREAD

**Issue by liaujianjie** [Ironclad/rivet#430]
### Feature Request

Currently, the code block only supports non-async code.

How can we add support for async code blocks?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Because the code block is unable to interact with the network or file system, what kinds of async operations would you run in it?

**Comment by kucukkanat** [comment]
@abrenneke why is it unable to interact with network? 
HTTP Call node can interact with the network. 
In my usecase I use oramasearch as an in memory vector db and need async functions to run for basic operations and in another case indexedDB with browser runner.

**Comment by abrenneke** [comment]
It's just a quirk of how `new Function` works in javascript, it's basically an `eval` that doesn't have any context of where it's running. Does the HTTP Call node not work?

**Comment by liaujianjie** [comment]
Previously I wanted to use a 3rd-party library that processed some data in Rivet. Unfortunately, the library only export a promise-returning function for the processing. I've since figured out a workaround for that issue so I will be closing this issue. Thanks for working on such a cool project!
