### ISSUE TITLE
[Bug]: Keyboard shortcuts do not work

### ISSUE THREAD

**Issue by remixer-dec** [Ironclad/rivet#435]
### What happened?

Cmd+c / cmd+x / backspace / delete buttons have no effect. Manually running the copy / paste commands from the navbar has no effect.
Things that do work: copying and pasting using a right-click, pasting using cmd+v, deleting using right click

### What was the expected functionality?

Keyboard shortcuts and navbar menu options should work correctly

### Describe your environment

MacOS sonoma 14.4.1, Rivet version: app-v1.7.12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Hm thanks for the report, I think I've noticed that too

**Comment by abrenneke** [comment]
Looks like copy/pasting is working for me, are you shift-clicking to select nodes? 
![2024-07-31 13 09 36](https://github.com/user-attachments/assets/e744feae-7955-4d39-8635-6049f8e1c036)

**Comment by abrenneke** [comment]
Added delete hotkey in 1acca66868676304b15c3213a6c6025ab9dd07fe

**Comment by remixer-dec** [comment]
Tried once again, copy paste does work with shift-selection, pretty sure I tested it the same way before reporting, but maybe there was something else affecting it and a restart helped, anyways, thanks for delete hotkey!
