### ISSUE TITLE
[Bug]: New prompt cache node #1

### ISSUE THREAD

**Issue by veloisgood** [Ironclad/rivet#445]
### What happened?

Not sure if these are technical bugs or "functional" ones. 
Cached prompt usually contains multiple back and forths between user and assistant. e.g user: hello how are you assitant: my name is Claude user: nice knowing you. 

cache in prompt mentions that current message+anything before would get cached. So how would I cache  a static chunk of my back and fort interactions ? Prompt node can only take one role at a time, so Id have to nodewithcacheON --> las connection in my assemble prompt --> Anthropic node = Error: Error processing ChatAnthropicNode: messages.0.content.0.text.cache_control: Extra inputs are not permitted (see picture for diagram on rivet) 
![image](https://github.com/user-attachments/assets/d97bb8f6-1c8d-4a5a-ac76-317c5c3c9dc7)
 

### What was the expected functionality?

For this particular case, based of how you want to implement the functionality, we should allow Anthropic node to "digest" an assemble prompt where inside one of the messages is marked as "cache from here to every other interaction before me". 

### Describe your environment

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by veloisgood** [comment]
See [[Bug]: New cache node #2](https://github.com/Ironclad/rivet/issues/446#top)  for detailed custom solution we implemented + proposed fix.

**Comment by abrenneke** [comment]
Added "Is last message cache breakpoint" to the Assemble Prompt node
