### ISSUE TITLE
[Feature]: HuggingFace / Other Custom Models

### ISSUE THREAD

**Issue by abrenneke** [Ironclad/rivet#85]
### Feature Request

Support custom models, perhaps via HuggingFace or another library out there that normalizes all the inputs to the models

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by remkolems** [comment]
For reference candidate purposes (local and/or on-premise LLM):

- [https://github.com/oobabooga/text-generation-webui](https://github.com/oobabooga/text-generation-webui)

**Comment by abrenneke** [comment]
Hugging face support has been added, and local LLMs I'll defer to #106
