### ISSUE TITLE
[Bug]: Documentation says node 16+, contributing.md says node 20+

### ISSUE THREAD

**Issue by gogwilt** [Ironclad/rivet#87]
### What happened?

Ran into issues running Rivet locally from source with `yarn dev`, with errors around tsx. Noted that we were using Node 18, based on the documentation page saying 16+ was OK (https://rivet.ironcladapp.com/docs/getting-started/installation). But then checked Contributing.md, and saw it said to use 20+

### What was the expected functionality?

Rivet did not run locally

### Describe your environment

MacOS, Node 18 (via nvm)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Docs updated with the above, and rough system requirements for running rivet
